version: '3'
services:
  api:
    container_name: api
    build: .
    ports:
     - "7890:7890"
    volumes:
     - .:/ms-reportjs
  redis:
    container_name: redis
    image: "redis:5.0.5-alpine"
    ports:
     - "6379:6379"