swagger: "2.0"
info:
  description: "This is a specification of microservice reportjs."
  version: "0.0.1"
  title: "MS ReportJS"
  contact:
    email: "ivan.augustoxs@gmail.com"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
host: "localhost:7890"
basePath: "/"
tags:
- name: "ms-reportjs"
  description: "Everything about the micro-service"
schemes:
- "http"
paths:
  /xlsx/{xlsxId}:
    get:
      tags:
      - "ms-reportjs"
      summary: "Retrive a report by ID"
      description: "Returns a report"
      operationId: "getReport"
      produces:
      - "application/json"
      parameters:
      - name: "xlsxId"
        in: "path"
        description: "ID of report"
        required: true
        type: "integer"
        format: "int64"
      responses:
        102:
          description: "Report is processing"
        200:
          description: "Successful operation"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Report not found"
  /xlsx:
    post:
      tags:
        - "ms-reportjs"
      summary: "Create report"
      operationId: "generateXlsx"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Request object"
        required: true
        schema:
          $ref: "#/definitions/Report"
      responses:
        400:
          description: "Bad params"
        201:
          description: "Created"
definitions:
  Report:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      id:
        type: "integer"
        format: "int64"
    xml:
      name: "Report"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"